[project]
name = "backend-2-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "swapnil-meshram-tech", email = "177468871+swapnil-meshram-tech@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
backend-2-0 = "backend_2_0:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
